name: Build and Push Docker Images

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and push amd64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-hadash:${{ steps.get_version.outputs.VERSION }}, ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-hadash:latest
          platforms: linux/amd64

      - name: Build and push arm64 image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-hadash:${{ steps.get_version.outputs.VERSION }}-arm64, ${{ secrets.DOCKER_HUB_USERNAME }}/nestjs-hadash:latest-arm64
          platforms: linux/arm64